### ISSUE TITLE
Update http to https in Mint DOI button functionality

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsrepo#103]
### Descriptive summary

Background: When the Mint DOI button is used under Curator Tools, the newly minted DOI is displayed at the end of Preferred Citation. Currently, the URL prefix displays "http://doi.org..."

Request: Although that link works, I believe "https://doi.org..." is a more secure redirect method. Also, for consistency for users, can we have the displayed URL be changed to https?

**Comment by gamontoya** [comment]
@VivianChu No rush, but do you have time next week to work on this?

**Comment by VivianChu** [comment]
@gamontoya - Yes, I have time next week to work on this.

**Comment by VivianChu** [comment]
@hjsyoo - Do you want me to change the UI to make the display link to show https or update the data in preferred citation to https ? 
For example - <dams:Note>
        <dams:type>preferred citation</dams:type>
        <rdf:value>Geological Data Center at Scripps Institution of Oceanography (2018). 7TOW05WT Seven Tow Leg 5 - Cruise Report. In Data from Scripps Research Expeditions 1953-2005. UC San Diego Library Digital Collections. http://doi.org/10.6075/J0Q23XG7</rdf:value>
      </dams:Note>

Do you also want to change the mint doi function to generate the https://doi.org.... instead of http://doi.org?

Thanks

**Comment by hjsyoo** [comment]
@VivianChu If you can do both, that'd be ideal. 1) Change the mint doi function so that when it adds the newly minted doi to Preferred Citation, it displays _and_ links to https://doi.org...  2) Update the text displays and links in all the Preferred Citation records so that instances of the prefix, http://doi.org or http://dx.doi.org are changed to https://doi.org.

Please note that there will be instances of the older prefixes in Related Publications and Related Resource, but I don't think we need to touch those fields at this time.

@arwenhutt We have some RDC records where Identifier was used to duplicate the DOI information contained in the Preferred Citation (e.g., https://library.ucsd.edu/dc/object/bb9285436q). We can update those, too, with the more secure prefix, but I'm not sure that there's value to having those Identifier fields populated, especially since we haven't used them consistently across collections. What do you think? What would be best here - remove those duplicate DOIs in Identifiers in a separate ticket, or update them now to the secure prefix?

@VivianChu Does this correctly address the questions you had for me?

**Comment by VivianChu** [comment]
@hjsyoo  - Yes, this correctly address the questions I had for you.  
I can do both.   For #2- if I update the metadata in the preferred citation field and re-index it , then the UI will automatically display the correct information.  I don't have to update damspas UI to do that.  I just need to find all records that have preferred citation field with doi.org link and update the metdata.  I think this field will also need to change to https - 
    <dams:note>
      <dams:Note>
        <dams:type>identifier</dams:type>
        <dams:displayLabel>DOI</dams:displayLabel>
        <rdf:value>http://doi.org/10.6075/J0Q23XG7</rdf:value>
      </dams:Note>
    </dams:note>
With 2 metadata change, are you going to use Update DOI function to re-send the data to ezid?

For #1, the change will be in damsrepo. 
I'll keep you posted when it's ready.

**Comment by hjsyoo** [comment]
Great, it's probably best to update Identifier, so if it's not too much effort, let's go ahead and do that now.
I shouldn't need to resend any data to EZID, because the only URL info we currently "send" is the (DAMS) ARK URL. On the first API call to EZID, I believe we just request a new DOI, which we then display in our UI. We shouldn't be sending the DOI (and certainly not the URL prefix) back to EZID.

**Comment by VivianChu** [comment]
@hjsyoo, @gamontoya - The metadata for the DOI records have been updated in prod.  Damsrepo has been updated to use https://doi.org... for identifier and preferred citation. It's deployed to staging. 
For example,
https://librarytest.ucsd.edu/dc/object/bd04139816  I used Mint DOI function and the DOI url is https now.

Here are some DOI records in production after re-indexing.
https://library.ucsd.edu/dc/object/bb1540812f
https://library.ucsd.edu/dc/object/bb11995109

Could you review them?  Thanks

**Comment by hjsyoo** [comment]
@VivianChu They're behaving perfectly. I updated DOI record on https://library.ucsd.edu/dc/object/bb1540812f, and it still looks fine. Thank you!

**Comment by VivianChu** [comment]
@hjsyoo - The update for Mint DOI function is not deployed to production yet.  There's no change in the Update DOI function. It's only deployed to staging.  I'll make a request to deploy it to production. You can test the Mint DOI button on staging for test record if you have one.  If not, I can load a test record and you can try that button.  What do you think?  Thanks

**Comment by hjsyoo** [comment]
Oh, right - I was just checking to make sure Update didn't touch the corrected display. There aren't actually very many objects on test that I can play around with without affecting the actual EZID record, because the Update function will redirect the DOI to the version on staging, which will break the DOI link for the public. No worries, though, I trust that everything works fine!

**Comment by VivianChu** [comment]
@hjsyoo - The update for Mint DOI function has been deployed to production. It's ready to use. Thanks

**Comment by hjsyoo** [comment]
@VivianChu Thanks so much!
