### ISSUE TITLE
Release 4.47

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/damsrepo#106]
## Descriptive Summary ##

Version: 4.47
Release Manager: @VivianChu 
Product Owner and Reviewer: @gamontoya
Operations: @jhriv or @rstanonik 

## To Verify ##

- [x] Update http to https in Mint DOI button functionality #103

**Comment by VivianChu** [comment]
@rstanonik / @jhriv - Could you deploy new damsrepo release to production at your earliest convenient? Thanks

**Comment by rstanonik** [comment]
Deployed this morning and tomcat restarted

**Comment by VivianChu** [comment]
Thanks @rstanonik
