### ISSUE TITLE
Stop counting subcollections as part of a collection's extent count

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsrepo#107]
## Description

DAMSRepo sub-collections in object counts when it should only count nunber of objects. 

## Example

- https://library.ucsd.edu/dc/collection/bb3039464b

Extent shows 98 objects when it should only list 95.

**Comment by gamontoya** [comment]
@abbypenn93  @lsitu I'm still seeing 98 objects although this ticket is closed.

- https://library.ucsd.edu/dc/collection/bb3039464b

**Comment by lsitu** [comment]
@gamontoya We haven't released the fix yet. Could you create a new release ticket for damsrepo? Thanks.
