### ISSUE TITLE
Check status of Public Solr Index for PAS

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsrepo#48]
## Issue:
It looks like the Solr index for PAS is not working. I'm waiting this week for 5 public collections to be added to the list, but they did not show up today (Thursday, 05/25)

## Rationale:
Every month I submit new UCSD Digital Collections content to Calisphere for harvesting. The collections need to be added to the Sorl index in order for harvesting to be done.

## Collections in Question:

- Edward Sheldon Barr Papers 
- Data from: Drift-Corrected Seafloor Vertical Deformation at Axial Seamount	
- Data from: Data from: Electrostatic interactions as mediators in the allosteric activation of PKA RIalpha
- Southern Ocean Carbon and Climate Observations and Modeling (SOCCOM) Float Data Archive
- Stuart Collection Photographs
- The Bangarang Project

**Comment by mcritchlow** [comment]
assigning to Longshou to investigate and re-index as needed.

**Comment by lsitu** [comment]
@rstanonik How often do we sync the prod solr on lib-hydratail.prod:8983 to the public solr core lib-metadata? It looks like the solr index in lib-metadata is a little outdated and it's still running on SOLR 4 at this time.

**Comment by gamontoya** [comment]
@lsitu Is this closeable? Is the auto-synch in place?

**Comment by rstanonik** [comment]
Yes, it will sync on the same schedule as before.

**Comment by lsitu** [comment]
@gamontoya I think we can close it. If we need another manual sync out of the automatic sync  once the metadata is fixed for https://github.com/ucsdlib/damspas/issues/324, we can work it out there. Thanks @rstanonik.
