### ISSUE TITLE
Investigate and resolve ingest/indexing to production

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsrepo#49]
## Issue:

Two objects were ingested to production on 05/25/17 (curator-only) and have not shown up

**8:29 AM
bb06511831**

**10:22 AM
bb9968674d**

ActiveMQ showed no jobs in the queue.

I then used DAMS Manager to re-index the objects (and the collection) and although I got an email saying it was successful, I saw the following error:

![fail](https://cloud.githubusercontent.com/assets/4314914/26472468/1ccf7e9c-415b-11e7-8595-00973927fc06.png)

ActiveMQ and DAMS Manager were restarted by Ron.

Ron checked the logs and reports this:

```
rstanonik [12:52 PM] 
I see this in the log many times.

[12:52] 
2017-05-25 11:37:39,677 INFO edu.ucsd.library.xdre.utils.DAMSClient: POST 
https://lib-hydratail-prod.ucsd.edu:8443/dams/api/objects/bb3210934b/index?format=json&ts=dams&priority=2&user=gamontoya&client=Custom+remotes%2F
origin%2Fmaster-0-ga42de56a9dae8ec98ab97e1f2b1d781d92896714: ERROR status code 500. Error Indexing failures. java.io.IOException: POST https://lib-hydratail-prod.ucsd.edu:8443/dams/api/objects/bb3210934b/index?format=json&ts=dams&priority=2&user=gamontoya&client=Custom+remotes%2
Forigin%2Fmaster-0-ga42de56a9dae8ec98ab97e1f2b1d781d92896714: ERROR status code 500. Error Indexing failures.
```
```rstanonik [12:58 PM] 
Earlier in the log I see this

[12:58] 
May 25, 2017 9:40:52 AM org.apache.catalina.realm.JNDIRealm authenticate
WARNING: Exception performing authentication
javax.naming.CommunicationException: Connection reset [Root exception is java.net.SocketException: Connection reset]; remaining name 'OU=Users,OU=University Library,DC=AD,DC=UCSD,DC=EDU'

**Comment by lsitu** [comment]
@rstanonik I think this error will occur when ActiveMQ restarted while tomcat for damsrepo hasn't been restarted properly. In this case, we had better restart tomcat for damsrepo (lib-hydratail-prod) for a clean run time environment, though you could reload config (http://lib-hydratail-prod:8080/dams/api/system/config) that could often make it work.

**Comment by lsitu** [comment]
@gamontoya I've re-indexed those two objects, and they are showing up now:
http://library.ucsd.edu/dc/object/bb06511831
http://library.ucsd.edu/dc/object/bb9968674d

**Comment by lsitu** [comment]
@mcritchlow I also created PR https://github.com/ucsdlib/damsmanager/pull/149 to catch the failed status for SOLR index. It's ready for review now. Thanks.
