### ISSUE TITLE
Addition of two roles to DAMS

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsrepo#57]
We would like to request the addition of two new role values:
- Co-Director
- Associate Director

These do not map to an external vocabulary so just need local arks, along the lines of how "principal investigator":
```
<dams:role>
<mads:Authority rdf:about="http://library.ucsd.edu/ark:/20775/bb5735317d">
<mads:authoritativeLabel>Principal investigator</mads:authoritativeLabel>
<mads:code>pri</mads:code>
</mads:Authority>
</dams:role>
```
I don't think we use the mads:code anywhere but if it's required by the system then we can use "cdr" (for Co-Director) and "adr" (for Associate Director)

**Comment by gamontoya** [comment]
@VivianChu Is this something you can do or does this require Longshou?

**Comment by lsitu** [comment]
@gamontoya @VivianChu I have one day break from the Fedora Sprint next Monday, and I think I can do it.

**Comment by gamontoya** [comment]
@lsitu Thank you Longshou. I'll assign to you.

**Comment by lsitu** [comment]
@gamontoya Sure. I'll work on it next Monday.

**Comment by lsitu** [comment]
@arwenhutt I've added those two roles you need to prod:
Co-Director: http://library.ucsd.edu/ark:/20775/bb67265096 (http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb67265096)
Associate Director: http://library.ucsd.edu/ark:/20775/bb5429571b (http://lib-hydratail-prod.ucsd.edu:8080/dams/api/objects/bb5429571b)

**Comment by arwenhutt** [comment]
Thanks @lsitu !  I verified that these are showing up/usable in production.  Since this was a rush request, I'm assuming they have not been added to the excel ingest tool in dams manager and we should create a separate ticket for that?

**Comment by lsitu** [comment]
@arwenhutt I think either creating a new ticket or updating the description text in this ticket for the new support in damsmanager will work.

**Comment by arwenhutt** [comment]
Closing this ticket, we'll create a new one for the ingest updates.
