### ISSUE TITLE
Update DOI function throws an error when geoLocationPoint data is present

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsrepo#87]
### Descriptive summary

When I try to mint or update a DOI record on an object with geoLocationPoint data, I get the following error:

Error updating DOI: error: bad request - datacite: metadata validation error: Element '{http://datacite.org/schema/kernel-4}geoLocationPoint': Character content other than whitespace is not allowed because the content type is 'element-only'., line 47

For example, https://library.ucsd.edu/dc/object/bb6930466p has point data and an existing DOI. When pushing the Update DOI Record button, I get the error above. Note that the EZID record, https://ezid.cdlib.org/id/doi:10.6075/J01V5BW2, currently has the point data because it was manually entered at the time of the original minting. I can't seem to update it now.

### Related work

https://github.com/ucsdlib/damsrepo/issues/74.

**Comment by hjsyoo** [comment]
@gamontoya This work is high priority for RDCP, but I removed the label because I don't remember how exactly we are using it.

**Comment by gamontoya** [comment]
@VivianChu Something for you to work on after UC DLFx and the long weekend.

**Comment by VivianChu** [comment]
@hjsyoo @gamontoya - The fix has been deployed to staging.  
Could you review it? https://librarytest.ucsd.edu/dc/object/bb6930466p
Here are the screen shot.  Thanks
Before the fix

![beforeFixGeoPointError](https://user-images.githubusercontent.com/1864660/58581519-97d04680-8204-11e9-8607-41cae40d82c1.png)

After the fix

![afterFixGeoPoint](https://user-images.githubusercontent.com/1864660/58581532-9dc62780-8204-11e9-8686-179943e25025.png)

![ezid](https://user-images.githubusercontent.com/1864660/58581569-adde0700-8204-11e9-9f73-5dc99e181dd4.png)

**Comment by gamontoya** [comment]
@VivianChu Looks good on staging!

**Comment by hjsyoo** [comment]
@VivianChu Agreed, it looks good! Thank you.

**Comment by VivianChu** [comment]
Thanks @gamontoya @hjsyoo for reviewing.  Currently I'm waiting for the change to get reviewed and merged into the code base.  Whenever it gets merged, I'll create a new release for production.

**Comment by VivianChu** [comment]
@hjsyoo @gamontoya - It works fine in production for me.  https://library.ucsd.edu/dc/object/bb6930466p
