### ISSUE TITLE
Fix recurring broken images bug

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damsrepo#88]
We have a fairly consistent bug that results in the following experience for damspas  users:

![image](https://user-images.githubusercontent.com/67506/57550425-301c8f00-731b-11e9-9b93-54111cdcbfe4.png)

The current remedy is that @rstanonik will restart the tomcat for damsrepo and, while this works, it is reactive.

So let's try and see if we can isolate the issue and fix it.

Please attach logs/etc. here so we can start sorting out how to diagnose this, enable extra logging in damsrepo and/or damspas, etc.

cc: @lsitu @rstanonik @jhriv

**Comment by mcritchlow** [comment]
Noting that @rstanonik is going to look into the possibility of adding Honeycomb monitoring to Java/Tomcat apps. If so we'll get that setup to hopefully help with this as well.

**Comment by mcritchlow** [comment]
@lsitu - Ron found https://docs.honeycomb.io/getting-data-in/java/ for getting Honeycomb setup on a Java app. I can create the Honeycomb datasets and give you that info. But I'm not sure what the best approach is of the 2 for integrating into damsrepo (and maybe damsmanager at some point too).

Here are the Honeycomb datasets (I/we can get you the API key separately, though it'll need to be private):
- 'Dams Repository - Staging'
- 'Dams Repository - Production'

**Comment by lsitu** [comment]
@mcritchlow Yes, it's an interesting bug, which happened too often recently. Not sure how that `ArrayIndexOutOfBoundsException` is triggered though. I will look into Honeycomb doc to see how to set it up for damsrepo.

**Comment by mcritchlow** [comment]
I think we may need some additional debug logging setup for damsrepo, from the current logs it doesn't seem like it'll be possible for us to easily track this down.

**Comment by lsitu** [comment]
@rstanonik / @mcritchlow What kind of information do we want to send to Honeycomb, something like request path, status, exception etc.? Also, should we just concentrate on sending the information for file requests at this time?

**Comment by lsitu** [comment]
@rstanonik / @mcritchlow Do you have any suggestions regarding what information we want to send to Honeycomb? It seems like we can add some logging to see whether it helps or not if we don't want to send much information to Honeycomb.
It looks like the issue is caused by the SimpleDateFormat this time, which is not thread safe. I think we can fix it. But I am not sure whether there is another issues that may cause this error or not since it seems like it's different from the case we inspected last year. I'll try to rewrite that block of codes for converting the ark to pair path since that could throw the error too. Does it sounds good to you as our first try to fix the problem?

**Comment by rstanonik** [comment]
Maybe start and end time of requests.
Size?  In case large requests (download mp4) is affecting performance.

It sounds as if you figured out this problem without honeycomb.  Is there any info that would have helped?

**Comment by lsitu** [comment]
@rstanonik It found some discussion regarding the SimpleDateFormat is not thread safe issue, which seems to be the major issue for the `ArrayIndexOutOfBoundsException` that got recently: https://stackoverflow.com/questions/6840803/why-is-javas-simpledateformat-not-thread-safe.

**Comment by mcritchlow** [comment]
@lsitu - that sounds like a fantastic start. as you said there may end up being other issues, but if you've isolated that then it would be great to try fixing it. Thanks!

**Comment by lsitu** [comment]
@mcritchlow / @rstanonik Per our discussions above, I've created PR https://github.com/ucsdlib/damsrepo/pull/89 to fix the broken image issue with the `ArrayIndexOutOfBoundException`. Hopefully there are no other hidden issues that could cause the problem. The PR is ready for review now. Thanks.

**Comment by gamontoya** [comment]
@lsitu Do you need a release ticket for this?
