### ISSUE TITLE
Release 4.44

### ISSUE THREAD

**Issue by VivianChu** [ucsdlib/damsrepo#91]
## Descriptive Summary

- Version: 4.44
- Release Manager: @VivianChu  
- Product Owner and Reviewer: @gamontoya
- Operations: @jhriv or @rstanonik
--------------
## To Verify

- [x]  #87  - Fix Update DOI function geoPoint error

**Comment by VivianChu** [comment]
@jhriv - Could you deploy new damsrepo release to production at your earliest convenient?  Could you also restart damsolrizer after you deploy damsrepo?  Thanks

**Comment by jhriv** [comment]
Deployed, solrizer restarted

**Comment by VivianChu** [comment]
Thanks John.
