### ISSUE TITLE
CLR suppressDiscovery access state not working as expected

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsrepo#99]
When dams:visibility is:
<dams:visibility>suppressDiscovery</dams:visibility>
The CLR is suppressed from discovery (removed from the public index) but it is also not viewable by the public.  

Collection Level Records should behave the same as object level records:
- not indexed for public searching
- viewable to the public

Related discussion in this ticket: https://github.com/ucsdlib/damspas/issues/719

**Comment by hjsyoo** [comment]
I added myself as an Assignee, only so I can watch this ticket.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsrepo/pull/100 to make the hidden suppressDiscovery CLR read accessible. Thanks.

**Comment by arwenhutt** [comment]
@jessicahilt can you add @remerjohnson to the ticket so that he can do the testing?  

@lsitu Just let him know when it's ready for testing and where to do that (production/qa).  

Thanks all!
